export const URL_PATH = {
  EMPTY: "",
  HOMEID: "home/:id",
  HOME: "home",
  MOD4: "until-module-4",
  SERVICES: "services",
  INJECTION: "services-injection",
  HTTPCLIENT: "services-httpclient",
  ROUTING: "routing-navigation",
  PRODUCTS: "products",
  PRODUCTSID: "products/:id",
  CONTACT: "contact",
  FORMS: "forms",
  VALIDATION: "validation",
  INCLASS: "inclass-pocs",
  LOGIN: "login",
  REGISTER: "register",
  LOGOUT: "logout",
  SERVERS: "servers",
  BY_TEMPLATE: "by_template",
  BY_REACTIVE: "by_reactive",
  ID: ":id",
  IDEDIT: ":id/edit",
  AUTH: "auth",
  MYPAGEID: "my-page/:id",
  BLOGS: "blogs",
  NEWBLOGS: "newblogs",
  OTHERBLOGS: "otherblogs",
  MYPAGE: "my-page",
  NOTFOUND: "not-found",
  OTHER: "**",
};

// { path: "external-employee/:id", component: ExternalEmployee },
